src/Entity/ArticleCategorie.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\JoinTable;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleCategorieRepository")
 */
class ArticleCategorie
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $article_categorie_id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $article_categorie_nom;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Article", mappedBy="categorie")
     */
    private $articles;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Image", inversedBy="articleCategorie", cascade={"persist", "remove"})
     * @ORM\JoinColumn(name="image_uri", referencedColumnName="image_uri", nullable=false)
     */
    private $image_uri;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\ArticleCategorie", inversedBy="categorie")
     * @ORM\JoinColumn(name="article_categorie_parent_id", referencedColumnName="article_categorie_id", nullable=true)
     */
    private $articleCategorie;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ArticleCategorie", mappedBy="articleCategorie")
     */
    private $categorie;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\ArticleCategorieCaracteristique", mappedBy="categories")
     */
    private $caracteristiques;

    public function __construct()
    {
        $this->articles = new ArrayCollection();
        $this->categorie = new ArrayCollection();
        $this->caracteristiques = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->article_categorie_id;
    }

    public function getArticleCategorieId(): ?int
    {
        return $this->article_categorie_id;
    }

    public function getArticleCategorieNom(): ?string
    {
        return $this->article_categorie_nom;
    }

    public function setArticleCategorieNom(string $article_categorie_nom): self
    {
        $this->article_categorie_nom = $article_categorie_nom;

        return $this;
    }

    /**
     * @return Collection|Article[]
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): self
    {
        if (!$this->articles->contains($article)) {
            $this->articles[] = $article;
            $article->setCategorie($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): self
    {
        if ($this->articles->contains($article)) {
            $this->articles->removeElement($article);
            // set the owning side to null (unless already changed)
            if ($article->getCategorie() === $this) {
                $article->setCategorie(null);
            }
        }

        return $this;
    }

    public function getImageUri(): ?Image
    {
        return $this->image_uri;
    }

    public function setImageUri(Image $image_uri): self
    {
        $this->image_uri = $image_uri;

        return $this;
    }

    public function getArticleCategorie(): ?self
    {
        return $this->articleCategorie;
    }

    public function setArticleCategorie(?self $articleCategorie): self
    {
        $this->articleCategorie = $articleCategorie;

        return $this;
    }

    /**
     * @return Collection|self[]
     */
    public function getCategorie(): Collection
    {
        return $this->categorie;
    }

    public function addCategorie(self $categorie): self
    {
        if (!$this->categorie->contains($categorie)) {
            $this->categorie[] = $categorie;
            $categorie->setArticleCategorie($this);
        }

        return $this;
    }

    public function removeCategorie(self $categorie): self
    {
        if ($this->categorie->contains($categorie)) {
            $this->categorie->removeElement($categorie);
            // set the owning side to null (unless already changed)
            if ($categorie->getArticleCategorie() === $this) {
                $categorie->setArticleCategorie(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|ArticleCategorieCaracteristique[]
     */
    public function getCaracteristiques(): Collection
    {
        return $this->caracteristiques;
    }

    public function addCaracteristique(ArticleCategorieCaracteristique $caracteristique): self
    {
        if (!$this->caracteristiques->contains($caracteristique)) {
            $this->caracteristiques[] = $caracteristique;
            $caracteristique->addCategory($this);
        }

        return $this;
    }

    public function removeCaracteristique(ArticleCategorieCaracteristique $caracteristique): self
    {
        if ($this->caracteristiques->contains($caracteristique)) {
            $this->caracteristiques->removeElement($caracteristique);
            $caracteristique->removeCategory($this);
        }

        return $this;
    }
}

src/Entity/Image.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ImageRepository")
 */
class Image
{
    /**
     * @ORM\Id()
     * @ORM\Column(type="string", length=255)
     */
    private $image_uri;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\ArticleCategorie", mappedBy="image_uri", cascade={"persist", "remove"})
     */
    private $articleCategorie;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Article", inversedBy="image_uri")
     * @ORM\JoinColumn(name="article_reference", referencedColumnName="article_reference", nullable=true)
     */
    private $article;

    public function getImageUri(): ?string
    {
        return $this->image_uri;
    }

    public function setImageUri( string $image_uri ): self
    {
        $this->image_uri = $image_uri;

        return $this;
    }

    public function getArticleCategorie(): ?ArticleCategorie
    {
        return $this->articleCategorie;
    }

    public function setArticleCategorie(ArticleCategorie $articleCategorie): self
    {
        $this->articleCategorie = $articleCategorie;

        // set the owning side of the relation if necessary
        if ($articleCategorie->getImageUri() !== $this) {
            $articleCategorie->setImageUri($this);
        }

        return $this;
    }

    public function getArticle(): ?Article
    {
        return $this->article;
    }

    public function setArticle(?Article $article): self
    {
        $this->article = $article;

        return $this;
    }
}

src/Controller/CategorieController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Entity\ArticleCategorie;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CategorieController extends AbstractController
{
    /**
     * @Route("/categorie/{id}", name="categorie")
     * @param Request $request
     * @param int $id
     * @return Response
     */
    public function show(Request $request, int $id )
    {
        // Nombre limite d'article par page
        $nb_article_max = 5;

        // Page par défaut
        $num_page = 1;

        // Récupération des repositories
        $repo_cat = $this->getDoctrine()->getRepository( ArticleCategorie::class);
        $repo_art = $this->getDoctrine()->getRepository( Article::class);

        // Récupération de la catégorie passer en paramètre
        $categorie = $repo_cat->find( $id );

        // Vérifie si la catégorie existe
        if( is_null( $categorie ) )
        {
            return $this->redirectToRoute('home');
        }

        if( is_integer( intval( $request->get('page') ) ) && $request->get('page') > 0)
        {
            $num_page = $request->get('page');
        }

        // Récupération des articles de la catégorie (Paginate)
        $articles = $repo_art->getArticlesPaginate( $categorie, $num_page, $nb_article_max );

        /**
         * Variable utile pour la pagination sur TWIG.
         * Calcul le nombre de page total en fonction du nombre d'article à afficher
         * Ceil permet d'arrondir au nombre au dessus
         */
        $nb_page_max = ceil( $articles->count() / $nb_article_max);

        return $this->render('categorie/show.html.twig', [
            'categorie'  => $categorie,
            'articles'   => $articles,
            'page_max'   => $nb_page_max,
            'num_page'   => $num_page
        ]);
    }
}

templates/categorie/index.html.twig
{% extends('base.html.twig') %}

templates/categorie/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ categorie.ArticleCategorieNom | capitalize }}{% endblock %}

{% block body %}
    <div class="row mb-3 overflow-hidden">
        <nav aria-label="breadcrumb" class="col-12 p-0">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ path('home') }}">Accueil</a></li>
                {% if categorie.articleCategorie is not null %}
                    <li class="breadcrumb-item"><a
                                href="{{ path('categorie', {id: categorie.articleCategorie.articleCategorieId}) }}">{{ categorie.articleCategorie.articleCategorieNom | capitalize }}</a>
                    </li>
                {% endif %}
                <li class="breadcrumb-item active"
                    aria-current="page">{{ categorie.ArticleCategorieNom | capitalize }}</li>
            </ol>
        </nav>

        <!-- Début Catégorie Parent -->
        {% if categorie.articleCategorie is null %}
                <div class="col-12 p-0">
                    <div class="card">
                        <h1 class="card-header">{{ categorie.articleCategorieNom | capitalize }}</h1>
                        <div class="card-body">
                            <div class="row">
                                {% for cat in categorie.categorie %}
                                    <div class="col-sm-12 col-md-4 text-center d-flex flex-column justify-content-between mb-4">
                                        <div class="card h-100">
                                            <div class="card-body text-center my-auto">
                                                <img class="img-fluid rounded"
                                                     src="{{ asset( cat.imageUri.imageUri ) }}"
                                                     alt="Image catégorie {{ cat.articleCategorieNom }}"/>
                                            </div>
                                            <h2 class="card-footer m-0">
                                                <a href="{{ path('categorie', { 'id': cat.id }) }}">
                                                    {{ cat.articleCategorieNom | capitalize }}
                                                </a>
                                            </h2>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
        {% endif %}
        <!-- Fin Catégorie Parent -->

        <!-- Début Catégorie avec parent -->
        {% if categorie.articleCategorie is not null %}
            <div class="col-md-3 col-lg-3 bg-primary rounded-left">
                <h2 class="text-center text-white">Filtrer les articles</h2>
            </div>
            <div class="col-md-9 col-lg-9 bg-white liste-article rounded-right">

                {% if articles | length == 0 and categorie.articleCategorie is not null %}
                    Aucun article dans cette catégorie
                {% endif %}

                {% for article in articles %}
                    <article class="row">
                        <div class="col-sm-12 col-md-4 col-lg-4">
                            <a href="{{ path('article', { id: article.ArticleReference }) }}">
                                <img class="img-fluid" src="{{ asset('images/alimentation.png') }}"
                                     alt="Article {{ article.ArticleReference }}"/>
                            </a>
                        </div>
                        <div class="col-sm-12 col-md-8 col-lg-8">
                            <div class="row">
                                <div class="col-sm-12 col-md-8">
                                    <a href="{{ path('article', { id: article.ArticleReference }) }}">
                                        {{ article.ArticleReference }}
                                    </a><br/>
                                    <p class="text-justify">
                                        {{ article.ArticleDescriptionCourte }}
                                    </p>
                                </div>
                                <div class="col-4">
                                    <div class="price mt-2"> {{ article.ArticlePrixHt }} €</div>

                                    <form class="mt-lg-3 mt-md-3 form-add-art">
                                        <div class="form-group">
                                            <div class="d-flex justify-content-center">
                                                <button class="btn-rem-qt-article">
                                                    <i class="fas fa-minus"></i>
                                                </button>
                                                <input type="hidden" name="article_reference"
                                                       value="{{ article.ArticleReference }}"/>
                                                <input type="number" name="article_quantite" min="1" value="1"
                                                       class="input-qt-article"/>
                                                <button class="btn-add-qt-article">
                                                    <i class="fas fa-plus"></i>
                                                </button>
                                            </div>

                                        </div>
                                        <div class="form-group text-right">
                                            <button class="btn btn-primary btn-add-cart">
                                                <i class="fas fa-cart-plus"></i>
                                            </button>
                                        </div>
                                    </form>

                                </div>
                            </div>
                        </div>
                    </article>
                {% endfor %}

                {% if articles | length > 0 %}
                    <nav class="mt-3">
                        <ul class="pagination justify-content-end">
                            <li class="page-item {{ num_page == 1 ? 'disabled' }}">
                                <a class="page-link"
                                   href="{{ path('categorie', {id: categorie.Id, page: num_page - 1}) }}">
                                    <i class="fas fa-angle-left"></i> </a>
                            </li>
                            {% for i in 1..page_max %}
                                <li class="page-item {{ num_page == i ? 'active' }}">
                                    <a class="page-link"
                                       href="{{ path('categorie', {id: categorie.Id, page: i}) }}">{{ i }}</a>
                                </li>
                            {% endfor %}
                            <li class="page-item {{ num_page == page_max ? 'disabled' }}">
                                <a class="page-link"
                                   href="{{ path('categorie', {id: categorie.Id, page: num_page + 1}) }}">
                                    <i class="fas fa-angle-right"></i> </a>
                            </li>
                        </ul>
                    </nav>
                {% endif %}
            </div>
        {% endif %}
        <!-- Fin Catégorie avec parent -->
    </div>
{% endblock %}

    {% block javascripts %}
        <script>
            $(function () {
                $('.btn-rem-qt-article').on('click', evt => {
                    evt.preventDefault();

                    let num = parseInt($($(evt.currentTarget).siblings()[1]).val());

                    if (num > 1) {
                        num -= 1;
                        $($(evt.currentTarget).siblings()[1]).val(num);
                    }
                });

                $('.btn-add-qt-article').on('click', evt => {
                    evt.preventDefault();

                    let num = parseInt($($(evt.currentTarget).siblings()[2]).val()) + 1;
                    $($(evt.currentTarget).siblings()[2]).val(num);
                });

                $('.form-add-art').on('click', '.btn-add-cart', evt => {
                    evt.preventDefault();

                    let formData = new FormData(evt.currentTarget.form);

                    $.ajax({
                        dataType: "json",
                        contentType: "application/json; charset=utf-8",
                        url: '{{ path('panier_add_article') }}',
                        type: 'POST',
                        data: JSON.stringify({
                            article_reference: formData.get('article_reference'),
                            article_quantite: formData.get('article_quantite')
                        }),
                        success: function () {
                            window.location = "../panier";
                        },
                        error: function () {

                        }
                    });
                });
            });
        </script>
    {% endblock %}