src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\JoinTable;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 */
class Article
{
    /**
     * @ORM\Id()
     * @ORM\Column(type="string", length=25)
     */
    private $article_reference;

    /**
     * @ORM\Column(type="string", length=80)
     */
    private $article_designation;

    /**
     * @ORM\Column(type="float")
     */
    private $article_prix_ht;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $article_description_courte;

    /**
     * @ORM\Column(type="text")
     */
    private $article_description_longue;

    /**
     * @ORM\Column(type="integer")
     */
    private $article_minimum_stock;

    /**
     * @ORM\Column(type="integer")
     */
    private $article_stock;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\ArticleCategorie", inversedBy="articles")
     * @ORM\JoinColumn(name="article_categorie_id", referencedColumnName="article_categorie_id", nullable=false)
     */
    private $categorie;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Image", mappedBy="article")
     */
    private $image_uri;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\ArticleMeta", inversedBy="articles")
     * @JoinTable(name="article_avoir_meta",
     *      joinColumns={@ORM\JoinColumn(name="article_reference", referencedColumnName="article_reference")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="article_meta_id", referencedColumnName="article_meta_id")}
     * )
     */
    private $meta;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ArticleAvoirPromotion", mappedBy="article")
     */
    private $hasPromotions;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\CommandeAvoirArticle", mappedBy="article")
     */
    private $commandeAvoirArticles;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Fournisseur", mappedBy="articles")
     */
    private $fournisseurs;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ArticleCaracteristique", mappedBy="article")
     */
    private $caracteristiques;

    public function __construct()
    {
        $this->image_uri = new ArrayCollection();
        $this->meta = new ArrayCollection();
        $this->hasPromotions = new ArrayCollection();
        $this->commandeAvoirArticles = new ArrayCollection();
        $this->fournisseurs = new ArrayCollection();
        $this->caracteristiques = new ArrayCollection();
    }

    public function getArticle_reference()
    {
        return $this->article_reference;
    }

    public function getArticleReference(): ?string
    {
        return $this->article_reference;
    }

    public function setArticleReference(string $article_reference): self
    {
        $this->article_reference = $article_reference;

        return $this;
    }

    public function getArticleDesignation(): ?string
    {
        return $this->article_designation;
    }

    public function setArticleDesignation(string $article_designation): self
    {
        $this->article_designation = $article_designation;

        return $this;
    }

    public function getArticlePrixHt(): ?float
    {
        return $this->article_prix_ht;
    }

    public function setArticlePrixHt(float $article_prix_ht): self
    {
        $this->article_prix_ht = $article_prix_ht;

        return $this;
    }

    public function getArticleDescriptionCourte(): ?string
    {
        return $this->article_description_courte;
    }

    public function setArticleDescriptionCourte(string $article_description_courte): self
    {
        $this->article_description_courte = $article_description_courte;

        return $this;
    }

    public function getArticleDescriptionLongue(): ?string
    {
        return $this->article_description_longue;
    }

    public function setArticleDescriptionLongue(string $article_description_longue): self
    {
        $this->article_description_longue = $article_description_longue;

        return $this;
    }

    public function getArticleMinimumStock(): ?int
    {
        return $this->article_minimum_stock;
    }

    public function setArticleMinimumStock(int $article_minimum_stock): self
    {
        $this->article_minimum_stock = $article_minimum_stock;

        return $this;
    }

    public function getArticleStock(): ?int
    {
        return $this->article_stock;
    }

    public function setArticleStock(int $article_stock): self
    {
        $this->article_stock = $article_stock;

        return $this;
    }

    public function getCategorie(): ?ArticleCategorie
    {
        return $this->categorie;
    }

    public function setCategorie(?ArticleCategorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImageUri(): Collection
    {
        return $this->image_uri;
    }

    public function addImageUri(Image $imageUri): self
    {
        if (!$this->image_uri->contains($imageUri)) {
            $this->image_uri[] = $imageUri;
            $imageUri->setArticle($this);
        }

        return $this;
    }

    public function removeImageUri(Image $imageUri): self
    {
        if ($this->image_uri->contains($imageUri)) {
            $this->image_uri->removeElement($imageUri);
            // set the owning side to null (unless already changed)
            if ($imageUri->getArticle() === $this) {
                $imageUri->setArticle(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|ArticleMeta[]
     */
    public function getMeta(): Collection
    {
        return $this->meta;
    }

    public function addMetum(ArticleMeta $metum): self
    {
        if (!$this->meta->contains($metum)) {
            $this->meta[] = $metum;
        }

        return $this;
    }

    public function removeMetum(ArticleMeta $metum): self
    {
        if ($this->meta->contains($metum)) {
            $this->meta->removeElement($metum);
        }

        return $this;
    }

    /**
     * @return Collection|ArticleAvoirPromotion[]
     */
    public function getHasPromotions(): Collection
    {
        return $this->hasPromotions;
    }

    public function addHasPromotion(ArticleAvoirPromotion $hasPromotion): self
    {
        if (!$this->hasPromotions->contains($hasPromotion)) {
            $this->hasPromotions[] = $hasPromotion;
            $hasPromotion->setArticle($this);
        }

        return $this;
    }

    public function removeHasPromotion(ArticleAvoirPromotion $hasPromotion): self
    {
        if ($this->hasPromotions->contains($hasPromotion)) {
            $this->hasPromotions->removeElement($hasPromotion);
            // set the owning side to null (unless already changed)
            if ($hasPromotion->getArticle() === $this) {
                $hasPromotion->setArticle(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|CommandeAvoirArticle[]
     */
    public function getCommandeAvoirArticles(): Collection
    {
        return $this->commandeAvoirArticles;
    }

    public function addCommandeAvoirArticle(CommandeAvoirArticle $commandeAvoirArticle): self
    {
        if (!$this->commandeAvoirArticles->contains($commandeAvoirArticle)) {
            $this->commandeAvoirArticles[] = $commandeAvoirArticle;
            $commandeAvoirArticle->setArticle($this);
        }

        return $this;
    }

    public function removeCommandeAvoirArticle(CommandeAvoirArticle $commandeAvoirArticle): self
    {
        if ($this->commandeAvoirArticles->contains($commandeAvoirArticle)) {
            $this->commandeAvoirArticles->removeElement($commandeAvoirArticle);
            // set the owning side to null (unless already changed)
            if ($commandeAvoirArticle->getArticle() === $this) {
                $commandeAvoirArticle->setArticle(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Fournisseur[]
     */
    public function getFournisseurs(): Collection
    {
        return $this->fournisseurs;
    }

    public function addFournisseur(Fournisseur $fournisseur): self
    {
        if (!$this->fournisseurs->contains($fournisseur)) {
            $this->fournisseurs[] = $fournisseur;
            $fournisseur->addArticle($this);
        }

        return $this;
    }

    public function removeFournisseur(Fournisseur $fournisseur): self
    {
        if ($this->fournisseurs->contains($fournisseur)) {
            $this->fournisseurs->removeElement($fournisseur);
            $fournisseur->removeArticle($this);
        }

        return $this;
    }

    /**
     * @return Collection|ArticleCaracteristique[]
     */
    public function getCaracteristiques(): Collection
    {
        return $this->caracteristiques;
    }

    public function addCaracteristique(ArticleCaracteristique $caracteristique): self
    {
        if (!$this->caracteristiques->contains($caracteristique)) {
            $this->caracteristiques[] = $caracteristique;
            $caracteristique->setArticle($this);
        }

        return $this;
    }

    public function removeCaracteristique(ArticleCaracteristique $caracteristique): self
    {
        if ($this->caracteristiques->contains($caracteristique)) {
            $this->caracteristiques->removeElement($caracteristique);
            // set the owning side to null (unless already changed)
            if ($caracteristique->getArticle() === $this) {
                $caracteristique->setArticle(null);
            }
        }

        return $this;
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use App\Entity\ArticleCategorie;
use App\Entity\ArticleMeta;
use App\Entity\Fournisseur;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('article_reference', TextType::class, [
                'required' => true,
                'label' => 'Numéro de référence'
            ])
            ->add('article_designation', TextType::class, [
                'required' => true,
                'label' => 'Désignation'
            ])
            ->add('article_prix_ht', MoneyType::class, [
                'required' => true,
                'label' => 'Prix'
            ])
            ->add('article_description_courte', TextType::class, [
                'required' => false,
                'label' => 'Description courte'
            ])
            ->add('article_description_longue', TextType::class, [
                'required' => false,
                'label' => 'Description longue'
            ])
            ->add('article_minimum_stock', NumberType::class, [
                'required' => true,
                'label' => 'Stock minimum'
            ])
            ->add('article_stock', NumberType::class, [
                'required' => true,
                'label' => 'Stock'
            ])
            ->add('categorie', EntityType::class, [
                'class'        => ArticleCategorie::class,
                'choice_label' => 'article_categorie_nom',
                'label'        => 'Catégorie',
                'required'     => true,
                'placeholder'  => 'Choisir catégorie'
            ])
            ->add('meta', EntityType::class, [
                'class'        => ArticleMeta::class,
                'choice_label' => 'article_meta_nom',
                'multiple'     => true,
                'label'        => 'Meta',
                'required'     => false
            ])
            ->add('fournisseurs', EntityType::class, [
                'class'        => Fournisseur::class,
                'choice_label' => 'fournisseur_nom',
                'multiple'     => true,
                'label'        => 'Fournisseurs',
                'required'     => false
            ])
            ->add('image_uri', FileType::class, [
                'required'     => false,
                'mapped'       => false,
                'constraints'  => [
                    new File([
                        'mimeTypes' => [
                            'image/jpeg',
                            'image/jpg',
                            'image/png'
                        ],
                        'mimeTypesMessage' => 'Seuls les formats JPEG, JPG et PNG sont autorisé'
                    ])
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;

class ArticleController extends AbstractController
{
    /**
     * @Route("/article/{id}", name="article")
     */
    public function index( $id )
    {
        $repo = $this->getDoctrine()->getRepository( Article::class );

        // Récupération de l'article
        $article = $repo->find( $id );

        if( is_null( $article ) )
        {
            throw new NotFoundHttpException('Cette article n\'existe pas');
        }

        return $this->render('article/index.html.twig', [
            'article'         => $article
        ]);
    }
}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ article.article_reference }}{% endblock %}

{% block body %}
    <div class="card">
        <h1 class="card-header">{{ article.article_reference }}</h1>
        <div class="card-body">
            <div class="row">
                <div class="col-md-4 col-lg-4">
                    {#                    <img src="{{ asset( article.imageUri.get(0)) }}" alt="Article {{ article.article_reference }}" />#}
                    <img src="{{ asset( 'images/carte-mere.jpg' ) }}" alt="Article {{ article.article_reference }}"/>
                </div>
                <div class="col-md-8 col-lg-8">
                    <div class="row">
                        <div class="col-md-6 col-lg-6">
                            <p class="text-justify">{{ article.articleDescriptionCourte }}</p>
                        </div>
                        <div class="col-md-6 col-lg-6 bg-primary rounded">
                            <p class="text-center prix-article">{{ article.articlePrixHt }}€</p>
                            {% if article.articleStock > 0 %}
                            <form class="mt-lg-3 mt-md-3 form-add-art">
                                <div class="form-group">
                                    <div class="d-flex justify-content-center">
                                        <button class="btn-rem-qt-article-show">
                                            <i class="fas fa-minus"></i>
                                        </button>
                                        <input type="hidden" name="article_reference"
                                               value="{{ article.ArticleReference }}"/>
                                        <input type="number" name="article_quantite" min="1" value="1"
                                               class="input-qt-article"/>
                                        <button class="btn-add-qt-article-show">
                                            <i class="fas fa-plus"></i>
                                        </button>
                                    </div>
                                </div>
                                {% endif %}

                                <div class="form-group">
                                    {% if article.articleStock > 0 %}
                                        <span class="stock text-success">
                                            En stock
                                        </span>
                                    {% else %}
                                        <span class="stock text-danger">
                                            Rupture de stock
                                        </span>
                                    {% endif %}
                                </div>

                                {% if article.articleStock > 0 %}
                                <div class="form-group text-center">
                                    <button class="btn btn-warning btn-add-cart w-75">
                                        Ajouter au panier
                                    </button>
                                </div>
                                {% endif %}
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-12">
                    <p class="text-justify">{{ article.articleDescriptionLongue }}</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

    {% block javascripts %}
        <script>
            $(function () {
                $('.btn-rem-qt-article-show').on('click', evt => {
                    evt.preventDefault();

                    let num = parseInt($($(evt.currentTarget).siblings()[1]).val());

                    if (num > 1) {
                        num -= 1;
                        $($(evt.currentTarget).siblings()[1]).val(num);
                    }
                });

                $('.btn-add-qt-article-show').on('click', evt => {
                    evt.preventDefault();

                    let num = parseInt($($(evt.currentTarget).siblings()[2]).val()) + 1;
                    $($(evt.currentTarget).siblings()[2]).val(num);
                });

                $('.form-add-art').on('click', '.btn-add-cart', evt => {
                    evt.preventDefault();

                    let formData = new FormData(evt.currentTarget.form);

                    $.ajax({
                        dataType: "json",
                        contentType: "application/json; charset=utf-8",
                        url: '{{ path('panier_add_article') }}',
                        type: 'POST',
                        data: JSON.stringify({
                            article_reference: formData.get('article_reference'),
                            article_quantite: formData.get('article_quantite')
                        }),
                        success: function () {
                            window.location = "../panier";
                        },
                        error: function () {

                        }
                    });
                });
            });
        </script>
    {% endblock %}