src/Entity/Commande.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CommandeRepository")
 */
class Commande
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $commande_reference;

    /**
     * @ORM\Column(type="datetime")
     */
    private $commande_date_creation;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $commande_date_paiement;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $commande_date_expedition;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="commandes")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="user_id",nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\TypePaiement", inversedBy="type_paiement")
     * @ORM\JoinColumn(name="type_paiement_id", referencedColumnName="type_paiement_id",nullable=false)
     */
    private $typePaiement;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\CommandeAvoirArticle", mappedBy="commande")
     */
    private $commandeAvoirArticles;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Adresse", inversedBy="commande_facture")
     * @ORM\JoinColumn(name="commande_adresse_facture", referencedColumnName="adresse_id",nullable=false)
     */
    private $commande_adresse_facture;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Adresse", inversedBy="commande_livraison")
     * @ORM\JoinColumn(name="commande_adresse_livraison", referencedColumnName="adresse_id",nullable=false)
     */
    private $commande_adresse_livraison;

    public function __construct()
    {
        $this->commandeAvoirArticles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->commande_reference;
    }

    public function getCommandeDateCreation(): ?\DateTimeInterface
    {
        return $this->commande_date_creation;
    }

    public function setCommandeDateCreation(\DateTimeInterface $commande_date_creation): self
    {
        $this->commande_date_creation = $commande_date_creation;

        return $this;
    }

    public function getCommandeDatePaiement(): ?\DateTimeInterface
    {
        return $this->commande_date_paiement;
    }

    public function setCommandeDatePaiement(?\DateTimeInterface $commande_date_paiement): self
    {
        $this->commande_date_paiement = $commande_date_paiement;

        return $this;
    }

    public function getCommandeDateExpedition(): ?\DateTimeInterface
    {
        return $this->commande_date_expedition;
    }

    public function setCommandeDateExpedition(?\DateTimeInterface $commande_date_expedition): self
    {
        $this->commande_date_expedition = $commande_date_expedition;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getTypePaiement(): ?TypePaiement
    {
        return $this->typePaiement;
    }

    public function setTypePaiement(?TypePaiement $typePaiement): self
    {
        $this->typePaiement = $typePaiement;

        return $this;
    }

    /**
     * @return Collection|CommandeAvoirArticle[]
     */
    public function getCommandeAvoirArticles(): Collection
    {
        return $this->commandeAvoirArticles;
    }

    public function addCommandeAvoirArticle(CommandeAvoirArticle $commandeAvoirArticle): self
    {
        if (!$this->commandeAvoirArticles->contains($commandeAvoirArticle)) {
            $this->commandeAvoirArticles[] = $commandeAvoirArticle;
            $commandeAvoirArticle->setCommande($this);
        }

        return $this;
    }

    public function removeCommandeAvoirArticle(CommandeAvoirArticle $commandeAvoirArticle): self
    {
        if ($this->commandeAvoirArticles->contains($commandeAvoirArticle)) {
            $this->commandeAvoirArticles->removeElement($commandeAvoirArticle);
            // set the owning side to null (unless already changed)
            if ($commandeAvoirArticle->getCommande() === $this) {
                $commandeAvoirArticle->setCommande(null);
            }
        }

        return $this;
    }

    public function getCommandeAdresseFacture(): ?Adresse
    {
        return $this->commande_adresse_facture;
    }

    public function setCommandeAdresseFacture(?Adresse $commande_adresse_facture): self
    {
        $this->commande_adresse_facture = $commande_adresse_facture;

        return $this;
    }

    public function getCommandeAdresseLivraison(): ?Adresse
    {
        return $this->commande_adresse_livraison;
    }

    public function setCommandeAdresseLivraison(?Adresse $commande_adresse_livraison): self
    {
        $this->commande_adresse_livraison = $commande_adresse_livraison;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields={"user_email"}, message="Un compte existe déjà avec cette adresse email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $user_id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $user_email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $user_password;

    /**
     * @var string La confirmation du mot de passe
     */
    private $confirm_password;

    /**
     * @ORM\Column(type="string", length=60)
     */
    private $user_nom;

    /**
     * @ORM\Column(type="string", length=60)
     */
    private $user_prenom;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $user_date_naissance;

    /**
     * @ORM\Column(type="datetime")
     */
    private $user_created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $user_updated_at;

    /**
     * @ORM\Column(type="string", length=1)
     */
    private $user_sexe;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Commande", mappedBy="user")
     */
    private $commandes;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Adresse", mappedBy="user")
     */
    private $adresses;

    public function __construct()
    {
        $this->commandes = new ArrayCollection();
        $this->adresses = new ArrayCollection();
        $this->user_created_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->user_id;
    }

    public function getUserId(): ?int
    {
        return $this->user_id;
    }

    public function getUserEmail(): ?string
    {
        return $this->user_email;
    }

    public function setUserEmail(string $user_email): self
    {
        $this->user_email = $user_email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->user_email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->user_password;
    }

    public function getUserPassword(): string
    {
        return (string) $this->user_password;
    }

    public function setUserPassword(string $password): self
    {
        $this->user_password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getUserNom(): ?string
    {
        return $this->user_nom;
    }

    public function setUserNom(string $user_nom): self
    {
        $this->user_nom = $user_nom;

        return $this;
    }

    public function getUserPrenom(): ?string
    {
        return $this->user_prenom;
    }

    public function setUserPrenom(string $user_prenom): self
    {
        $this->user_prenom = $user_prenom;

        return $this;
    }

    public function getUserDateNaissance(): ?\DateTimeInterface
    {
        return $this->user_date_naissance;
    }

    public function setUserDateNaissance(?\DateTimeInterface $user_date_naissance): self
    {
        $this->user_date_naissance = $user_date_naissance;

        return $this;
    }

    public function getUserCreatedAt(): ?\DateTimeInterface
    {
        return $this->user_created_at;
    }

    public function setUserCreatedAt(\DateTimeInterface $user_created_at): self
    {
        $this->user_created_at = $user_created_at;

        return $this;
    }

    public function getUserUpdatedAt(): ?\DateTimeInterface
    {
        return $this->user_updated_at;
    }

    public function setUserUpdatedAt(?\DateTimeInterface $user_updated_at): self
    {
        $this->user_updated_at = $user_updated_at;

        return $this;
    }

    public function getConfirmPassword(): string
    {
        return $this->confirm_password;
    }

    public function setConfirmPassword(string $confirm_password): self
    {
        $this->confirm_password = $confirm_password;

        return $this;
    }

    public function getUserSexe(): ?string
    {
        return $this->user_sexe;
    }

    public function setUserSexe(string $user_sexe): self
    {
        $this->user_sexe = $user_sexe;

        return $this;
    }

    /**
     * @return Collection|Commande[]
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes[] = $commande;
            $commande->setUser($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->contains($commande)) {
            $this->commandes->removeElement($commande);
            // set the owning side to null (unless already changed)
            if ($commande->getUser() === $this) {
                $commande->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Adresse[]
     */
    public function getAdresses(): Collection
    {
        return $this->adresses;
    }

    public function addAdress(Adresse $adress): self
    {
        if (!$this->adresses->contains($adress)) {
            $this->adresses[] = $adress;
            $adress->setUser($this);
        }

        return $this;
    }

    public function removeAdress(Adresse $adress): self
    {
        if ($this->adresses->contains($adress)) {
            $this->adresses->removeElement($adress);
            // set the owning side to null (unless already changed)
            if ($adress->getUser() === $this) {
                $adress->setUser(null);
            }
        }

        return $this;
    }


}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\Adresse;
use App\Form\AddAdresseFormType;
use App\Form\UserInformationFormType;
use App\Form\UserPasswordFormType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class UserController extends AbstractController
{
    /**
     * @Route("/compte", name="user_account")
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     * @throws \Symfony\Component\Form\Exception\LogicException
     */
    public function index(Request $request) : Response
    {
        // Récupération de l'utilisateur
        $user = $this->getUser();

        $form = $this->createForm(UserInformationFormType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('user_account');
        }

        return $this->render('user/index.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/compte/mot-de-passe", name="user_password")
     * @param Request $request
     * @return Response
     * @throws \Symfony\Component\Form\Exception\LogicException
     * @throws \Symfony\Component\Form\Exception\RuntimeException
     */
    public function indexPassword(Request $request, UserPasswordEncoderInterface $passwordEncoder) : Response
    {
        // Récupération de l'utilisateur
        $user = $this->getUser();

        $form = $this->createForm(UserPasswordFormType::class, $user);
        $form->handleRequest($request);

        //$encoderService = $this->container->get('');
        //$match = $passwordEncoder->isPasswordValid($user->getPassword(), $form->get('old_password'));

        // Vérification du mot de passe
        //if( ! $match )
        //{
        //    $form->addError(new FormError('L\'ancien mot de passe ne correspond pas'));
        //}

        if ($form->isSubmitted() && $form->isValid()) {
            $user->setUserPassword(
                $passwordEncoder->encodePassword(
                    $user,
                    $form->get('user_password')->getData()
                )
            );
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('user_account');
        }

        return $this->render('user/password.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/compte/adresses", name="user_adresses")
     */
    public function indexAdresses(Request $request) : Response
    {
        return $this->render('user/adresse.html.twig', [
            'adresses' => $this->getUser()->getAdresses()
        ]);
    }

    /**
     * @Route("/compte/adresse/ajout", name="user_add_adresse")
     */
    public function addAdresse(Request $request) : Response
    {
        // Récupération de l'utilisateur
        $user = $this->getUser();

        $adresse = new Adresse();
        $form = $this->createForm(AddAdresseFormType::class, $adresse);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            return $this->redirectToRoute('user_adresses');
        }

        return $this->render('user/adresse-add.html.twig', [
            'form' => $form->createView()
        ]);
    }

}

templates/user/adresse-add.html.twig
{% extends 'user/base.user.html.twig' %}

{% block titre %}Création d'une adresse <a href="{{ path('user_adresses') }}" class="float-right" title="Revenir aux adresses"><i class="fas fa-chevron-circle-left"></i></a>{% endblock %}

{% block content %}
    <div class="row">
        {{ form(form) }}
    </div>
{% endblock %}

templates/user/adresse.html.twig
{% extends 'user/base.user.html.twig' %}

{% block titre %}Mes adresses <a href="{{ path('user_add_adresse') }}" class="float-right" title="Ajouter une adresse"><i class="fas fa-plus-circle"></i></a>{% endblock %}

{% block content %}
    <div class="row">
        {% if adresses | length == 0 %}
        <div class="border text-center p-5">
            <b>Vous n'avez pas encore d'adresse.</b>
        </div>
        {% else %}
        {% endif %}
    </div>
{% endblock %}

templates/user/base.user.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon compte{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-4 col-lg-4">
            <ul class="list-group">
                <li class="list-group-item {{ app.request.get('_route') == 'user_account' ? 'active' }}">
                    <a href="{{ path('user_account') }}">Mon compte</a>
                </li>
                <li class="list-group-item {{ app.request.get('_route') == 'user_commandes' ? 'active' }}">
                    <a href="{{ path('user_commandes') }}">Mes commandes</a>
                </li>
                <li class="list-group-item  {{ app.request.get('_route') == 'user_adresses' ? 'active' }}">
                    <a href="{{ path('user_adresses') }}">Mes adresses</a>
                </li>
                <li class="list-group-item {{ app.request.get('_route') == 'user_password' ? 'active' }}">
                    <a href="{{ path('user_password') }}">Mot de passe</a>
                </li>
                <li class="list-group-item">
                    <a href="{{ path('app_logout') }}">Déconnexion</a>
                </li>
            </ul>
        </div>
        <div class="col-md-8 col-lg-8">
            <div class="card">
                <h1 class="card-header">{% block titre %}{% endblock %}</h1>
                <div class="card-body">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/user/commande.html.twig
{% extends 'user/base.user.html.twig' %}

{% block titre %}Mes commandes{% endblock %}

{% block content %}
    {% if commandes | length == 0 %}
        <div class="border text-center p-5">
            <b>Vous n'avez pas de commande.</b>
        </div>
    {% else %}
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Référence</th>
                <th class="text-center">Date de commande</th>
                <th class="text-center">Montant total</th>
                <th>Statut</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for commande in commandes %}
                <tr>
                    <td>{{ commande.id }}</td>
                    <td class="text-center">{{ commande.commandeDateCreation | date('d-m-yy') }}</td>
                    <td class="text-center"><b>1000€</b></td>
                    <td>
                        {% if commande.commandeDatePaiement is not null and commande.commandeDateExpedition is null %}
                            En préparation
                        {% elseif  commande.commandeDatePaiement is not null and commande.commandeDateExpedition is not null %}
                            Expédiée
                        {% else %}
                            En attente de paiement
                        {% endif %}
                    </td>
                    <td>
                        <a href="#">
                            Consulter
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endif %}
{% endblock %}

templates/user/index.html.twig
{% extends 'user/base.user.html.twig' %}

{% block titre %}Mes informations{% endblock %}

{% block content %}

    {{ form_start(form) }}
    <div class="form-row">
        <div class="col-md-12">
            {{ form_widget(form.user_sexe) }}
            {{ form_errors(form.user_sexe) }}
        </div>
        <div class="col-md-6">
            {{ form_label(form.user_nom) }}
            {{ form_widget(form.user_nom) }}
            {{ form_errors(form.user_nom) }}
        </div>
        <div class="col-md-6">
            {{ form_label(form.user_prenom) }}
            {{ form_widget(form.user_prenom) }}
            {{ form_errors(form.user_prenom) }}
        </div>
        <div class="col-md-6">
            {{ form_label(form.user_email) }}
            {{ form_widget(form.user_email) }}
            {{ form_errors(form.user_email) }}
        </div>
        <div class="col-md-6">
            {{ form_label(form.user_date_naissance) }}
            {{ form_widget(form.user_date_naissance) }}
            {{ form_errors(form.user_date_naissance) }}
        </div>
    </div>
    <button class="btn btn-primary">{{ button_label|default('Sauvegarder') }}</button>
    {{ form_end(form) }}
{% endblock %}

templates/user/password.html.twig
{% extends 'user/base.user.html.twig' %}

{% block titre %}Modification du mot de passe{% endblock %}

{% block content %}
    {{ form_start(form) }}
    <div class="form-row">
        <div class="col-md-12">
            {{ form_label(form.old_password) }}
            {{ form_widget(form.old_password) }}
            {{ form_errors(form.old_password) }}
        </div>
        <div class="col-md-12">
            {{ form_widget(form.user_password) }}
            {{ form_errors(form.user_password) }}
        </div>
    </div>
    <button class="btn btn-primary">{{ button_label|default('Sauvegarder') }}</button>
    {{ form_end(form) }}
{% endblock %}